correction 00 for ex:0

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,14 +1,24 @@
 #!/usr/bin/env bash
-# Transfers a file from Holberton's client to another.
-# Accepts four arguments:
-#+   path to the file to be transferred.
-#+   IP of the server to transfer the file to.
-#+   username that scp connects with.
-#+   path to the SSH private key that scp uses.
+# This script transfers a file from a client to a server using scp.
 
-if [ $# -lt 4 ]
-then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# Check if the number of arguments is less than 4
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assigning arguments to variables
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key="$4"
+
+# Transfer the file using scp
+scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip:~/"
+
+# Check if scp command was successful
+if [ $? -eq 0 ]; then
+    echo "File transferred successfully to $username@$server_ip:~/"
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+    echo "Error: File transfer failed."
 fi
